### ISSUE TITLE
Little License Question

### ISSUE THREAD

**Issue by jaedson-barbosa** [hayeswise/Leaflet.PointInPolygon#6]
Hi, I'm going to use your library in my university project and I was wondering if it is necessary to put some copyright information on the page.

**Comment by hayeswise** [comment]
Hi Jaedson, 
Rather than copyright, in your list of references, provide a link to the GitHub project. Also, if the project is available on the internet, I'd like to take a look. I take it the PointInPolygon was useful!  
Thanks, Brian

**Comment by jaedson-barbosa** [comment]
Hi, the project will still take about 1 month to be presentable, but I will not forget to send the link here when everything is ready.
